<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="/public/ru/education.xsl" type="text/xsl"?>
<!DOCTYPE educations [
    <!ELEMENT educations (education+)>
    <!ELEMENT education (school,label,period)>

    <!ELEMENT school (name, logo)>
    <!ELEMENT label (#PCDATA)>
    <!ELEMENT period (#PCDATA)>

    <!ELEMENT name (#PCDATA)>

    <!ELEMENT logo EMPTY>
    <!ATTLIST logo link CDATA #REQUIRED>
]>

<educations>
    <education>
        <school>
            <name>Sup Galilée - университет Sorbonne Paris Nord</name>
            <logo link="/assets/images/sup_galilee.png"/>
        </school>
        <label>Цикл компьютерной инженерии</label>
        <period>С сентября 2020 года</period>
    </education>
    <education>
        <school>
            <name>Institut Galilée - университет Sorbonne Paris Nord</name>
            <logo link="/assets/images/institut_galilee.png"/>
        </school>
        <label>Второй курс Бакалавр наук в области компьютерных наук</label>
        <period>2019 - 2020</period>
    </education>
    <education>
        <school>
            <name>университет Gaston Berger, Sénégal</name>
            <logo link="/assets/images/ugb.png"/>
        </school>
        <label>Второй курс бакалавриата Математика Физика Компьютерные науки</label>
        <period>2017 - 2019</period>
    </education>
</educations>